version: '3.8'
services:
  db:
    container_name: db-ansor
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rahasia123
      MYSQL_DATABASE: goes_ansor
      MYSQL_USER: bosku
      MYSQL_PASSWORD: P@rahasia123
    command: --max_allowed_packet=120M
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ansor-network

  redis:
    container_name: redis-ansor
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ansor-network

  nginx:
    container_name: nginx-ansor
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - db
      - redis
    networks:
      - ansor-network

volumes:
  mysql_data:

networks:
  ansor-network:
    driver: bridge
    name: ansor-network
