version: '3.8'
services:
  db:
    container_name: db-ansor
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max_allowed_packet=120M
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ansor-network

  redis:
    container_name: redis-ansor
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ansor-network

volumes:
  mysql_data:

networks:
  ansor-network:
    driver: bridge
    name: ansor-network
